version: 2
updates:
  # ────────────────────────────────────────────────────────────────────────────
  # Go modules (arena-cache itself and any example/ tools)
  # ────────────────────────────────────────────────────────────────────────────
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(deps):"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      go-runtime:
        patterns:
          - "golang.org/*"
          - "github.com/golang/*"
      go-linters:
        patterns:
          - "honnef.co/*"
          - "github.com/dominikh/*"
    labels:
      - "go"
      - "dependencies"
      - "automerge"

  # ────────────────────────────────────────────────────────────────────────────
  # GitHub Actions – keep CI + Release workflows up-to-date
  # ────────────────────────────────────────────────────────────────────────────
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps):"
    labels:
      - "github-actions"
      - "dependencies"

  # ────────────────────────────────────────────────────────────────────────────
  # Docker – track base images used in build/docker/Dockerfile
  # ────────────────────────────────────────────────────────────────────────────
  - package-ecosystem: "docker"
    directory: "/build/docker"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker):"
    labels:
      - "docker"
      - "dependencies"

  # ────────────────────────────────────────────────────────────────────────────
  # NPM – only for docs site if custom plugins are added later
  # (disabled by default, uncomment if /docs/package.json appears)
  # ────────────────────────────────────────────────────────────────────────────
  # - package-ecosystem: "npm"
  #   directory: "/docs"
  #   schedule:
  #     interval: "weekly"
