##
# GoReleaser v2 configuration for arena-cache
# -------------------------------------------
# Generates cross-compiled binaries for the CLI tool `arena-cache-inspect`,
# archives them, cosigns the checksum file, and attaches everything to a
# GitHub Release.  Multi-arch Docker images are built separately in the
# workflow.
##

version: 2
project_name: arena-cache-inspect

env:
  - CGO_ENABLED=0 # static build for every OS/arch

# ────────────────────────────────────────────────────────────────
# Builds
# ────────────────────────────────────────────────────────────────
builds:
  - id: inspect
    main: ./cmd/arena-cache-inspect
    binary: arena-cache-inspect
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{ .Version }}
    hooks:
      pre: echo "building {{ .ProjectName }} {{ .Version }}"

# ────────────────────────────────────────────────────────────────
# Archives
# ────────────────────────────────────────────────────────────────
archives:
  - id: default
    builds: [inspect]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

# ────────────────────────────────────────────────────────────────
# Checksums + Cosign signature
# ────────────────────────────────────────────────────────────────
checksum:
  name_template: checksums.txt

signs:
  - id: cosign
    artifacts: checksum
    cmd: cosign
    args:
      - sign
      - --key=$COSIGN_PRIVATE_KEY
      - "{{ .ArtifactPath }}"
    signature: "{{ .ArtifactPath }}.sig"

# ────────────────────────────────────────────────────────────────
# GitHub Release
# ────────────────────────────────────────────────────────────────
release:
  name_template: v{{ .Version }}
  draft: false
  changelog:
    use: git
    sort: asc
    filters:
      exclude:
        - "^docs:.*"
        - "^chore:.*"
        - "^ci:.*"
        - "^build:deps.*"

# ────────────────────────────────────────────────────────────────
# Homebrew tap (optional)
# ────────────────────────────────────────────────────────────────
brews:
  - name: homebrew-tap
    tap:
      owner: "{{ .GithubOwner }}"
    commit_author:
      name: GitHub Actions
      email: actions@github.com
    description: arena-cache inspector CLI
    homepage: "https://github.com/{{ .GithubOwner }}/arena-cache-inspect"
    test: arena-cache-inspect -h
