project_name: arena-cache-inspect

builds:
  - id: default
    main: ./cmd/myapp/main.go

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

signs:
  - id: cosign-blob
    artifacts: checksum
    cmd: cosign
    args:
      - sign-blob
      - --yes # ok для cosign v2.*
      - --key=cosign.key
      - --output-signature={{ .ArtifactPath }}.sig
      - "{{ .ArtifactPath }}" # ← строка, без лишних пробелов
    env:
      - COSIGN_PASSWORD

# ───────────────── GitHub Release ─────────────────
release:
  name_template: v{{ .Version }}
  draft: false

# ───────────────── Changelog ──────────────────────
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:.*"
      - "^chore:.*"
      - "^ci:.*"
      - "^build:deps.*"

# ──────────────── Homebrew tap ────────────────────
brews:
  - repository:
      owner: "{{ .GithubOwner }}"
      name: homebrew-tap
    commit_author:
      name: GitHub Actions
      email: actions@github.com
    commit_msg_template: "brew: update {{ .ProjectName }} to {{ .Tag }}"
    description: arena-cache inspector CLI
    homepage: "https://github.com/{{ .GithubOwner }}/arena-cache-inspect"
    test: arena-cache-inspect -h
