##
# GoReleaser v2 configuration for arena-cache
# -------------------------------------------
# Builds multi-platform binaries for `arena-cache-inspect`, creates archives,
# signs the checksum file with Cosign, and attaches everything to a GitHub
# release.  Docker images are built in the workflow, not here.
##

version: 2
project_name: arena-cache-inspect

env:
  - CGO_ENABLED=0 # static build

# ────────────────────────────────────────────────────────────────
# Builds
# ────────────────────────────────────────────────────────────────
builds:
  - id: inspect
    main: ./cmd/arena-cache-inspect
    binary: arena-cache-inspect
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{ .Version }}
    hooks:
      pre: echo "building {{ .ProjectName }} {{ .Version }}"

# ────────────────────────────────────────────────────────────────
# Archives
# ────────────────────────────────────────────────────────────────
archives:
  - id: default
    builds: [inspect]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

# ────────────────────────────────────────────────────────────────
# Checksums + Cosign signature
# ────────────────────────────────────────────────────────────────
checksum:
  name_template: checksums.txt

signs:
  - id: cosign
    artifacts: checksum
    cmd: cosign
    args:
      - sign
      - --key=$COSIGN_PRIVATE_KEY
      - "{{ .Path }}"
    signature: "{{ .Path }}.sig"

# ────────────────────────────────────────────────────────────────
# GitHub Release
# ────────────────────────────────────────────────────────────────
release:
  name_template: v{{ .Version }}
  draft: false

# Separate changelog section (root-level in v2).
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:.*"
      - "^chore:.*"
      - "^ci:.*"
      - "^build:deps.*"

# ────────────────────────────────────────────────────────────────
# Homebrew tap
# ────────────────────────────────────────────────────────────────
brews:
  - repository:
      owner: "{{ .GithubOwner }}"
      name: homebrew-tap
    commit_author:
      name: GitHub Actions
      email: actions@github.com
    commit_msg_template: "brew: update {{ .ProjectName }} to {{ .Tag }}"
    description: arena-cache inspector CLI
    homepage: "https://github.com/{{ .GithubOwner }}/arena-cache-inspect"
    test: arena-cache-inspect -h
